server:
  port: 8082

security:
  oauth2:
    client:
      clientId: client_2
      clientSecret: secret_2
      userAuthorizationUri: http://app.sso.com:8080/oauth/authorize
      accessTokenUri: http://app.sso.com:8080/oauth/token
    resource:
      userInfoUri: http://app.sso.com:8080/oauth/me