server:
  port: 8088

spring:
  application:
    name: hikari-dubbo-consumer

dubbo:
  application:
    version: 1.0.0
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache

