server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client_1
      client-secret: secret_1
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
      registered-redirect-uri: http://localhost:8081/
      use-current-uri: true
    resource:
      id: clientA
      user-info-uri: http://localhost:8080/oauth/user-info
