server:
  port: 8081

security:
  oauth2:
    client:
      client-id: client_1
      client-secret: secret_1
      grant-type: authorization_code
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      id: clientA
      user-info-uri: http://localhost:8080/oauth/user-info
