server:
  port: 8081

oauth2-server: http://127.0.0.1:8080

security:
  oauth2:
    client:
      clientId: client_1
      clientSecret: secret_1
      accessTokenUri: ${oauth2-server}/oauth/token
      userAuthorizationUri: ${oauth2-server}/oauth/authorize
#      useCurrentUri: true
#      registeredRedirectUri: http://localhost:8081/login
    resource:
      userInfoUri: ${oauth2-server}/oauth/me