spring:
  application:
    name: hikari-dubbo-provider

dubbo:
  application:
    version: 1.0.0
  scan:
    base-packages: io.hikari.dubbo.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
    optimizer: io.hikari.dubbo.api.serialize.SerializationOptimizerImpl
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache