server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/simple_transaction?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      minimumIdle: 5
      idleTimeout: 600000
      maximumPoolSize: 10
      autoCommit: true
      poolName: CustomHikariCP
      maxLifetime: 1800000
      connectionTimeout: 30000
      connectionTestQuery: SELECT 1

mybatis:
  mapper-locations: classpath:mapper/*.xml