/*
 * This file is generated by jOOQ.
 */
package io.hikari.jooq.domain.tables;


import io.hikari.jooq.domain.Hikari;
import io.hikari.jooq.domain.tables.records.OauthRefreshTokenRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthRefreshToken extends TableImpl<OauthRefreshTokenRecord> {

    private static final long serialVersionUID = -1261231358;

    /**
     * The reference instance of <code>hikari.oauth_refresh_token</code>
     */
    public static final OauthRefreshToken OAUTH_REFRESH_TOKEN = new OauthRefreshToken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OauthRefreshTokenRecord> getRecordType() {
        return OauthRefreshTokenRecord.class;
    }

    /**
     * The column <code>hikari.oauth_refresh_token.token_id</code>. 通过MD5加密后的refresh_token
     */
    public final TableField<OauthRefreshTokenRecord, String> TOKEN_ID = createField("token_id", org.jooq.impl.SQLDataType.VARCHAR(256), this, "通过MD5加密后的refresh_token");

    /**
     * The column <code>hikari.oauth_refresh_token.token</code>. 存储将OAuth2RefreshToken.java对象序列化后的二进制数据.
     */
    public final TableField<OauthRefreshTokenRecord, byte[]> TOKEN = createField("token", org.jooq.impl.SQLDataType.BLOB, this, "存储将OAuth2RefreshToken.java对象序列化后的二进制数据.");

    /**
     * The column <code>hikari.oauth_refresh_token.authentication</code>. 存储将OAuth2Authentication.java对象序列化后的二进制数据.
     */
    public final TableField<OauthRefreshTokenRecord, byte[]> AUTHENTICATION = createField("authentication", org.jooq.impl.SQLDataType.BLOB, this, "存储将OAuth2Authentication.java对象序列化后的二进制数据.");

    /**
     * Create a <code>hikari.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken() {
        this(DSL.name("oauth_refresh_token"), null);
    }

    /**
     * Create an aliased <code>hikari.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken(String alias) {
        this(DSL.name(alias), OAUTH_REFRESH_TOKEN);
    }

    /**
     * Create an aliased <code>hikari.oauth_refresh_token</code> table reference
     */
    public OauthRefreshToken(Name alias) {
        this(alias, OAUTH_REFRESH_TOKEN);
    }

    private OauthRefreshToken(Name alias, Table<OauthRefreshTokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private OauthRefreshToken(Name alias, Table<OauthRefreshTokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OauthRefreshToken(Table<O> child, ForeignKey<O, OauthRefreshTokenRecord> key) {
        super(child, key, OAUTH_REFRESH_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Hikari.HIKARI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthRefreshToken as(String alias) {
        return new OauthRefreshToken(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthRefreshToken as(Name alias) {
        return new OauthRefreshToken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthRefreshToken rename(String name) {
        return new OauthRefreshToken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OauthRefreshToken rename(Name name) {
        return new OauthRefreshToken(name, null);
    }
}
