server:
  port: 8081

security:
  oauth2:
    client:
      clientId: client_1
      clientSecret: secret_1
      userAuthorizationUri: http://127.0.0.1:8080/oauth/authorize
      accessTokenUri: http://127.0.0.1:8080/oauth/token
    resource:
      userInfoUri: http://127.0.0.1:8080/oauth/me