server:
  port: 8080

security:
  oauth2:
    client-id: client
    client-secret: secret
    scopes: all,app
    grant-types: authorization_code,client_credentials,password,refresh_token
    validity-seconds: 7200
    refresh-seconds: 7200



