server:
  port: 8080

security:
  oauth2:
    client-id: client
    client-secret: secret
    scopes: all,app
    grant-types: authorization_code,client_credentials,password,refresh_token
    validity-seconds: 7200
    refresh-seconds: 7200

swagger:
  enable: true
  api-info:
    author: fetaxyu
    contact: https://github.com/fetaxyu
    email: fetaxy@gmail.com
    title: OAuth2 InMemory
    description: OAuth2 InMemory Mode
    url: https://fetaxyu.github.io
    version: 1.0


