/*
 * This file is generated by jOOQ.
 */
package io.hikari.jooq.domain.tables.records;


import io.hikari.jooq.domain.tables.OauthApprovals;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OauthApprovalsRecord extends TableRecordImpl<OauthApprovalsRecord> implements Record6<String, String, String, String, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = -1875181416;

    /**
     * Setter for <code>hikari.oauth_approvals.userId</code>.
     */
    public void setUserid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.userId</code>.
     */
    public String getUserid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>hikari.oauth_approvals.clientId</code>.
     */
    public void setClientid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.clientId</code>.
     */
    public String getClientid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hikari.oauth_approvals.scope</code>.
     */
    public void setScope(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.scope</code>.
     */
    public String getScope() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hikari.oauth_approvals.status</code>.
     */
    public void setStatus(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.status</code>.
     */
    public String getStatus() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hikari.oauth_approvals.expiresAt</code>.
     */
    public void setExpiresat(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.expiresAt</code>.
     */
    public LocalDateTime getExpiresat() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>hikari.oauth_approvals.lastModifiedAt</code>.
     */
    public void setLastmodifiedat(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>hikari.oauth_approvals.lastModifiedAt</code>.
     */
    public LocalDateTime getLastmodifiedat() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, String, String, String, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return OauthApprovals.OAUTH_APPROVALS.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OauthApprovals.OAUTH_APPROVALS.CLIENTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return OauthApprovals.OAUTH_APPROVALS.SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return OauthApprovals.OAUTH_APPROVALS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field5() {
        return OauthApprovals.OAUTH_APPROVALS.EXPIRESAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field6() {
        return OauthApprovals.OAUTH_APPROVALS.LASTMODIFIEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getClientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component5() {
        return getExpiresat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component6() {
        return getLastmodifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getClientid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value5() {
        return getExpiresat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value6() {
        return getLastmodifiedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value1(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value2(String value) {
        setClientid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value3(String value) {
        setScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value4(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value5(LocalDateTime value) {
        setExpiresat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord value6(LocalDateTime value) {
        setLastmodifiedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OauthApprovalsRecord values(String value1, String value2, String value3, String value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OauthApprovalsRecord
     */
    public OauthApprovalsRecord() {
        super(OauthApprovals.OAUTH_APPROVALS);
    }

    /**
     * Create a detached, initialised OauthApprovalsRecord
     */
    public OauthApprovalsRecord(String userid, String clientid, String scope, String status, LocalDateTime expiresat, LocalDateTime lastmodifiedat) {
        super(OauthApprovals.OAUTH_APPROVALS);

        set(0, userid);
        set(1, clientid);
        set(2, scope);
        set(3, status);
        set(4, expiresat);
        set(5, lastmodifiedat);
    }
}
