/*
 * This file is generated by jOOQ.
 */
package io.hikari.jooq.domain.tables.records;


import io.hikari.jooq.domain.tables.TbStockBasics;

import java.math.BigDecimal;
import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TbStockBasicsRecord extends UpdatableRecordImpl<TbStockBasicsRecord> implements Record14<Long, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, Integer> {

    private static final long serialVersionUID = 620649750;

    /**
     * Setter for <code>hikari.tb_stock_basics.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.stock_code</code>. 股票代码
     */
    public void setStockCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.stock_code</code>. 股票代码
     */
    public String getStockCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.company_name</code>. 公司名称
     */
    public void setCompanyName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.company_name</code>. 公司名称
     */
    public String getCompanyName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.industry</code>. 所属行业
     */
    public void setIndustry(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.industry</code>. 所属行业
     */
    public String getIndustry() {
        return (String) get(3);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.area</code>. 地区
     */
    public void setArea(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.area</code>. 地区
     */
    public String getArea() {
        return (String) get(4);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.pe</code>. 市盈率
     */
    public void setPe(BigDecimal value) {
        set(5, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.pe</code>. 市盈率
     */
    public BigDecimal getPe() {
        return (BigDecimal) get(5);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.outstanding</code>. 流通股本(亿)
     */
    public void setOutstanding(BigDecimal value) {
        set(6, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.outstanding</code>. 流通股本(亿)
     */
    public BigDecimal getOutstanding() {
        return (BigDecimal) get(6);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.totals</code>. 总股本(亿)
     */
    public void setTotals(BigDecimal value) {
        set(7, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.totals</code>. 总股本(亿)
     */
    public BigDecimal getTotals() {
        return (BigDecimal) get(7);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.total_assets</code>. 总资产(万)
     */
    public void setTotalAssets(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.total_assets</code>. 总资产(万)
     */
    public BigDecimal getTotalAssets() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.liquid_assets</code>. 流动资产
     */
    public void setLiquidAssets(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.liquid_assets</code>. 流动资产
     */
    public BigDecimal getLiquidAssets() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.reserved</code>. 公积金
     */
    public void setReserved(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.reserved</code>. 公积金
     */
    public BigDecimal getReserved() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.reserved_per_share</code>. 每股公积金
     */
    public void setReservedPerShare(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.reserved_per_share</code>. 每股公积金
     */
    public BigDecimal getReservedPerShare() {
        return (BigDecimal) get(11);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.launch_time</code>. 上市日期
     */
    public void setLaunchTime(LocalDate value) {
        set(12, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.launch_time</code>. 上市日期
     */
    public LocalDate getLaunchTime() {
        return (LocalDate) get(12);
    }

    /**
     * Setter for <code>hikari.tb_stock_basics.del_flag</code>. 是否删除 1-删除 0-正常
     */
    public void setDelFlag(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>hikari.tb_stock_basics.del_flag</code>. 是否删除 1-删除 0-正常
     */
    public Integer getDelFlag() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<Long, String, String, String, String, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, BigDecimal, LocalDate, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return TbStockBasics.TB_STOCK_BASICS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TbStockBasics.TB_STOCK_BASICS.STOCK_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TbStockBasics.TB_STOCK_BASICS.COMPANY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TbStockBasics.TB_STOCK_BASICS.INDUSTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return TbStockBasics.TB_STOCK_BASICS.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field6() {
        return TbStockBasics.TB_STOCK_BASICS.PE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field7() {
        return TbStockBasics.TB_STOCK_BASICS.OUTSTANDING;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field8() {
        return TbStockBasics.TB_STOCK_BASICS.TOTALS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field9() {
        return TbStockBasics.TB_STOCK_BASICS.TOTAL_ASSETS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field10() {
        return TbStockBasics.TB_STOCK_BASICS.LIQUID_ASSETS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return TbStockBasics.TB_STOCK_BASICS.RESERVED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return TbStockBasics.TB_STOCK_BASICS.RESERVED_PER_SHARE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field13() {
        return TbStockBasics.TB_STOCK_BASICS.LAUNCH_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return TbStockBasics.TB_STOCK_BASICS.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component6() {
        return getPe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component7() {
        return getOutstanding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component8() {
        return getTotals();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component9() {
        return getTotalAssets();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component10() {
        return getLiquidAssets();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getReserved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getReservedPerShare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component13() {
        return getLaunchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStockCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCompanyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value6() {
        return getPe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value7() {
        return getOutstanding();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value8() {
        return getTotals();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value9() {
        return getTotalAssets();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value10() {
        return getLiquidAssets();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getReserved();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getReservedPerShare();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value13() {
        return getLaunchTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value1(Long value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value2(String value) {
        setStockCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value3(String value) {
        setCompanyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value4(String value) {
        setIndustry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value5(String value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value6(BigDecimal value) {
        setPe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value7(BigDecimal value) {
        setOutstanding(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value8(BigDecimal value) {
        setTotals(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value9(BigDecimal value) {
        setTotalAssets(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value10(BigDecimal value) {
        setLiquidAssets(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value11(BigDecimal value) {
        setReserved(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value12(BigDecimal value) {
        setReservedPerShare(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value13(LocalDate value) {
        setLaunchTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord value14(Integer value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TbStockBasicsRecord values(Long value1, String value2, String value3, String value4, String value5, BigDecimal value6, BigDecimal value7, BigDecimal value8, BigDecimal value9, BigDecimal value10, BigDecimal value11, BigDecimal value12, LocalDate value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TbStockBasicsRecord
     */
    public TbStockBasicsRecord() {
        super(TbStockBasics.TB_STOCK_BASICS);
    }

    /**
     * Create a detached, initialised TbStockBasicsRecord
     */
    public TbStockBasicsRecord(Long id, String stockCode, String companyName, String industry, String area, BigDecimal pe, BigDecimal outstanding, BigDecimal totals, BigDecimal totalAssets, BigDecimal liquidAssets, BigDecimal reserved, BigDecimal reservedPerShare, LocalDate launchTime, Integer delFlag) {
        super(TbStockBasics.TB_STOCK_BASICS);

        set(0, id);
        set(1, stockCode);
        set(2, companyName);
        set(3, industry);
        set(4, area);
        set(5, pe);
        set(6, outstanding);
        set(7, totals);
        set(8, totalAssets);
        set(9, liquidAssets);
        set(10, reserved);
        set(11, reservedPerShare);
        set(12, launchTime);
        set(13, delFlag);
    }
}
