server:
  port: 8082

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: secret_2
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
      registered-redirect-uri: http://localhost:8082/
      use-current-uri: true
    resource:
      id: clientB
      user-info-uri: http://localhost:8080/oauth/user-info
