server:
  port: 8082

oauth2-server: http://localhost:8080

security:
  oauth2:
    client:
      clientId: client_2
      clientSecret: secret_2
      userAuthorizationUri: ${oauth2-server}/oauth/authorize
      accessTokenUri: ${oauth2-server}/oauth/token
      registeredRedirectUri: http://localhost:8082/
      useCurrentUri: true
    resource:
      id: clientB
      userInfoUri: ${oauth2-server}/oauth/me
