server:
  port: 8082

security:
  oauth2:
    client:
      client-id: client_2
      client-secret: secret_2
      grant-type: authorization_code
      user-authorization-uri: http://localhost:8080/oauth/authorize
      access-token-uri: http://localhost:8080/oauth/token
    resource:
      id: clientB
      user-info-uri: http://localhost:8080/oauth/user-info
