server:
  port: 8080

spring:
  application:
    name: dubbo-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/incubator_projects?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&rewriteBatchedStatements=true&useAffectedRows=true&useSSL=false&requireSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    max-active: 50
    initial-size: 1
    max-wait: 30000
    min-idle: 1
    filters: mergeStat,wall,slf4j,config
    validation-query: select 'x'

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.warless.incubator.dubbo.provider.pojo.po

dubbo:
  application:
    name: ${spring.application.name}
  provider:
    loadbalance: roundrobin
  scan:
    base-packages: org.warless.incubator.dubbo.provider.service
  protocol:
    name: dubbo
    port: 20880
    serialization: kryo
    optimizer: org.warless.incubator.dubbo.provider.config.SerializationOptimizerImpl
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
  service:
    version: 1.0.0
